#!/bin/sh
exec 2>&1

PATH=/command:/sbin:/bin:/usr/sbin:/usr/bin

echo "Running shutdown script $0:"
echo 'Waiting for services to stop...'
sv force-stop /service/*
sv exit /service/*

if [ -x /etc/runit/reboot ] ;then
  /etc/rc.d/rc.6
else
  /etc/rc.d/rc.0
fi
